import { collection, doc, getDoc, getDocs, orderBy, query, runTransaction, setDoc, Timestamp, where, type Firestore, type QueryConstraint } from "firebase/firestore";
import type { Account, Category, FinalizedSettlement, Household, HouseholdConfigVersion, HouseholdMember, Id, Project, RecurringTemplate, SettlementPeriod, SettlementPool, Transaction } from "../../domain/types";
import { validateTransaction } from "../../domain/validation";
import type { AuditEvent, BudgetRepository, TransactionDateQuery } from "../BudgetRepository";
import { assertValidBudgetExport, type BudgetExportV1 } from "../../services/export";
import { fromFirestoreData, toFirestoreData } from "./converters";

const paths = { members: "members", accounts: "accounts", categories: "categories", projects: "projects", settlementPools: "settlementPools", configHistory: "configHistory", transactions: "transactions", settlementPeriods: "settlementPeriods", settlements: "settlements", recurringTemplates: "recurringTemplates", auditLog: "auditLog" } as const;

export class FirestoreBudgetRepository implements BudgetRepository {
  constructor(private readonly db: Firestore, private readonly appVersion = "0.1.0") {}
  private household(h: Id) { return doc(this.db, "households", h); }
  private col(h: Id, name: string) { return collection(this.household(h), name); }
  private item(h: Id, name: string, id: Id) { return doc(this.col(h, name), id); }
  private async one<T>(h: Id, name: string, id: Id): Promise<T> { const snap = await getDoc(this.item(h, name, id)); if (!snap.exists()) throw new Error(`${name}/${id} not found`); return fromFirestoreData<T>({ id: snap.id, ...snap.data() }); }
  private async all<T>(h: Id, name: string): Promise<T[]> { const snap = await getDocs(this.col(h, name)); return snap.docs.map((d) => fromFirestoreData<T>({ id: d.id, ...d.data() })); }
  private async put<T extends { id: Id }>(h: Id, name: string, value: T) { const { id, ...data } = value; await setDoc(this.item(h, name, id), toFirestoreData(data), { merge: true }); }
  async getHousehold(h: Id) { const snap = await getDoc(this.household(h)); if (!snap.exists()) throw new Error("Household not found"); return fromFirestoreData<Household>({ id: snap.id, ...snap.data() }); }
  async saveHousehold(h: Id, v: Household) { await setDoc(this.household(h), toFirestoreData(v), { merge: true }); }
  async getMembers(h: Id) { return this.all<HouseholdMember>(h, paths.members); } async saveMember(h: Id, v: HouseholdMember) { await this.put(h, paths.members, v); }
  async getAccounts(h: Id) { return this.all<Account>(h, paths.accounts); } async saveAccount(h: Id, v: Account) { await this.put(h, paths.accounts, v); }
  async getCategories(h: Id) { return this.all<Category>(h, paths.categories); } async saveCategory(h: Id, v: Category) { await this.put(h, paths.categories, v); }
  async getProjects(h: Id) { return this.all<Project>(h, paths.projects); } async saveProject(h: Id, v: Project) { await this.put(h, paths.projects, v); }
  async getSettlementPools(h: Id) { return this.all<SettlementPool>(h, paths.settlementPools); } async saveSettlementPool(h: Id, v: SettlementPool) { await this.put(h, paths.settlementPools, v); }
  async getCurrentConfig(h: Id) { const current = await this.one<HouseholdConfigVersion & { versionId?: Id }>(h, "config", "current"); return current.versionId ? this.getConfigVersion(h, current.versionId) : current; }
  async getConfigForDate(h: Id, effectiveAt: string) { const candidates = (await this.listConfigHistory(h)).filter((config) => config.effectiveFrom <= effectiveAt); if (candidates.length) return candidates[candidates.length - 1]; return this.getCurrentConfig(h); }
  async getConfigVersion(h: Id, id: Id) { return this.one<HouseholdConfigVersion>(h, paths.configHistory, id); }
  async saveConfig(h: Id, v: HouseholdConfigVersion, reason?: string) { const value = reason === undefined ? v : { ...v, reason }; const currentValue = { versionId: value.id, ...value }; await runTransaction(this.db, async (tx) => { const historyRef = this.item(h, paths.configHistory, value.id); const currentRef = this.item(h, "config", "current"); const history = await tx.get(historyRef); const current = await tx.get(currentRef); if (history.exists() && JSON.stringify(fromFirestoreData(history.data())) !== JSON.stringify(value)) throw new Error("Config history is immutable"); tx.set(historyRef, toFirestoreData(value), { merge: false }); if (!current.exists() || value.effectiveFrom <= new Date().toISOString()) tx.set(currentRef, toFirestoreData(currentValue), { merge: false }); }); }
  async listConfigHistory(h: Id) { return (await this.all<HouseholdConfigVersion>(h, paths.configHistory)).sort((a, b) => a.version - b.version); }
  async getSettlementPeriod(h: Id, id: Id) { return this.one<SettlementPeriod>(h, paths.settlementPeriods, id); }
  async listSettlementPeriods(h: Id) { return (await this.all<SettlementPeriod>(h, paths.settlementPeriods)).sort((a, b) => b.startDate.localeCompare(a.startDate)); }
  async saveSettlementPeriod(h: Id, v: SettlementPeriod, expected?: string) { await runTransaction(this.db, async (tx) => { const ref = this.item(h, paths.settlementPeriods, v.id); const snap = await tx.get(ref); if (expected && snap.exists() && fromFirestoreData<SettlementPeriod>(snap.data()).updatedAt !== expected) throw new Error("Concurrency conflict: settlement period changed"); tx.set(ref, toFirestoreData(v), { merge: false }); }); }
  async saveBootstrap(h: Id, period: SettlementPeriod, transactions: Transaction[]) { await runTransaction(this.db, async (tx) => { const periodRef = this.item(h, paths.settlementPeriods, period.id); if ((await tx.get(periodRef)).exists()) throw new Error("Concurrency conflict: month already bootstrapped"); tx.set(periodRef, toFirestoreData(period), { merge: false }); for (const value of transactions) tx.set(this.item(h, paths.transactions, value.id), toFirestoreData(value), { merge: false }); }); }
  async listTransactionsForPeriod(h: Id, p: Id) { const snap = await getDocs(query(this.col(h, paths.transactions), where("settlementPeriodId", "==", p), orderBy("economicDate", "asc"))); return snap.docs.map((d) => fromFirestoreData<Transaction>({ id: d.id, ...d.data() })); }
  async getTransaction(h: Id, id: Id) { return this.one<Transaction>(h, paths.transactions, id); }
  async saveTransaction(h: Id, v: Transaction, expected?: string) { const validation = validateTransaction(v, { members: await this.getMembers(h), accounts: await this.getAccounts(h), categories: await this.getCategories(h), projects: await this.getProjects(h), settlementPools: await this.getSettlementPools(h) }); if (!validation.valid) throw new Error(`Invalid transaction: ${validation.errors.join("; ")}`); await runTransaction(this.db, async (tx) => { const ref = this.item(h, paths.transactions, v.id); const snap = await tx.get(ref); if (expected && snap.exists() && fromFirestoreData<Transaction>(snap.data()).updatedAt !== expected) throw new Error("Concurrency conflict: transaction changed"); const periods = new Set<Id>(); const old = snap.exists() ? fromFirestoreData<Transaction>(snap.data()).settlementPeriodId : undefined; if (old) periods.add(old); if (v.settlementPeriodId) periods.add(v.settlementPeriodId); const periodValues: Array<[Id, SettlementPeriod]> = []; for (const periodId of periods) { const periodSnap = await tx.get(this.item(h, paths.settlementPeriods, periodId)); if (periodSnap.exists()) { const period = fromFirestoreData<SettlementPeriod>({ id: periodSnap.id, ...periodSnap.data() }); if (period.status === "finalized") throw new Error("Finalized period transactions cannot be edited until reopened"); periodValues.push([periodId, period]); } } tx.set(ref, toFirestoreData(v), { merge: false }); for (const [periodId, period] of periodValues) tx.set(this.item(h, paths.settlementPeriods, periodId), toFirestoreData({ ...period, updatedAt: new Date().toISOString(), updatedByUid: v.updatedByUid }), { merge: false }); }); }
  async archiveTransaction(h: Id, id: Id, actorUid: string, reason = "Archived") { const tx = await this.getTransaction(h, id); tx.status = "excluded"; tx.updatedByUid = actorUid; tx.updatedAt = new Date().toISOString(); await this.saveTransaction(h, tx); await this.appendAuditEvent(h, { id: `audit-${id}-${Date.now()}`, eventType: "transaction deleted/excluded", entityType: "transaction", entityId: id, performedByUid: actorUid, timestamp: new Date().toISOString(), summary: reason }); }
  private async filtered(h: Id, field: string, value: Id, range?: TransactionDateQuery) { const clauses: QueryConstraint[] = [where(field, "==", value)]; if (range?.from) clauses.push(where("economicDate", ">=", Timestamp.fromDate(new Date(range.from)))); if (range?.to) clauses.push(where("economicDate", "<=", Timestamp.fromDate(new Date(range.to)))); const snap = await getDocs(query(this.col(h, paths.transactions), ...clauses, orderBy("economicDate", "asc"))); return snap.docs.map((d) => fromFirestoreData<Transaction>({ id: d.id, ...d.data() })); }
  async listTransactionsByProject(h: Id, p: Id) { return this.filtered(h, "projectId", p); } async listTransactionsByAccount(h: Id, a: Id, r?: TransactionDateQuery) { return this.filtered(h, "accountId", a, r); } async listTransactionsByCategory(h: Id, c: Id, r?: TransactionDateQuery) { return this.filtered(h, "categoryId", c, r); }
  async getFinalizedSettlementForPeriod(h: Id, p: Id) { const values = (await this.all<FinalizedSettlement>(h, paths.settlements)).filter((s) => s.settlementPeriodId === p).sort((a, b) => b.version - a.version); return values[0] ?? null; }
  async saveSettlement(h: Id, v: FinalizedSettlement) { const ref = this.item(h, paths.settlements, v.id); if ((await getDoc(ref)).exists()) throw new Error("Finalized settlement snapshots are immutable"); await setDoc(ref, toFirestoreData(v)); }
  async commitFinalization(h: Id, settlement: FinalizedSettlement, period: SettlementPeriod, audit: AuditEvent, expected: string) { await runTransaction(this.db, async (tx) => { const periodRef = this.item(h, paths.settlementPeriods, period.id); const settlementRef = this.item(h, paths.settlements, settlement.id); const current = await tx.get(periodRef); if (!current.exists() || fromFirestoreData<SettlementPeriod>(current.data()).updatedAt !== expected) throw new Error("Concurrency conflict: period changed during finalization"); if ((await tx.get(settlementRef)).exists()) throw new Error("Finalized settlement snapshots are immutable"); tx.set(settlementRef, toFirestoreData(settlement), { merge: false }); tx.set(periodRef, toFirestoreData(period), { merge: false }); tx.set(this.item(h, paths.auditLog, audit.id), toFirestoreData(audit), { merge: false }); }); }
  async getSettlement(h: Id, id: Id) { return this.one<FinalizedSettlement>(h, paths.settlements, id); }
  async getRecurringTemplates(h: Id) { return this.all<RecurringTemplate>(h, paths.recurringTemplates); } async saveRecurringTemplate(h: Id, v: RecurringTemplate) { await this.put(h, paths.recurringTemplates, v); }
  async listAuditLog(h: Id) { return (await this.all<AuditEvent>(h, paths.auditLog)).sort((a, b) => a.timestamp.localeCompare(b.timestamp)); } async appendAuditEvent(h: Id, v: AuditEvent) { const ref = this.item(h, paths.auditLog, v.id); if ((await getDoc(ref)).exists()) throw new Error("Audit events are immutable"); await setDoc(ref, toFirestoreData(v), { merge: false }); }
  async exportAll(h: Id): Promise<BudgetExportV1> { return { format: "household-budget-export", schemaVersion: 1, exportedAt: new Date().toISOString(), appVersion: this.appVersion, household: await this.getHousehold(h), members: await this.getMembers(h), accounts: await this.getAccounts(h), categories: await this.getCategories(h), projects: await this.getProjects(h), settlementPools: await this.getSettlementPools(h), currentConfig: await this.getCurrentConfig(h), configHistory: await this.listConfigHistory(h), transactions: await this.all<Transaction>(h, paths.transactions), settlementPeriods: await this.listSettlementPeriods(h), settlements: await this.all<FinalizedSettlement>(h, paths.settlements), recurringTemplates: await this.getRecurringTemplates(h) as RecurringTemplate[], auditLog: await this.listAuditLog(h) }; }
  async restoreAll(h: Id, raw: BudgetExportV1, actorUid: string) { assertValidBudgetExport(raw); const value = raw; const existing = await getDoc(this.household(h)); const existingCollections = await Promise.all(Object.values(paths).map((name) => getDocs(this.col(h, name)))); if (existing.exists() || existingCollections.some((snap) => !snap.empty)) throw new Error("Restore target must be an empty household"); const refs: Array<[string, string, unknown]> = [["households", h, { ...value.household, id: h }], ...value.members.map((v) => [paths.members, v.id, v] as [string, string, unknown]), ...value.accounts.map((v) => [paths.accounts, v.id, v] as [string, string, unknown]), ...value.categories.map((v) => [paths.categories, v.id, v] as [string, string, unknown]), ...value.projects.map((v) => [paths.projects, v.id, v] as [string, string, unknown]), ...value.settlementPools.map((v) => [paths.settlementPools, v.id, v] as [string, string, unknown]), ...value.configHistory.map((v) => [paths.configHistory, v.id, v] as [string, string, unknown]), ...value.settlementPeriods.map((v) => [paths.settlementPeriods, v.id, v] as [string, string, unknown]), ...value.transactions.map((v) => [paths.transactions, v.id, v] as [string, string, unknown]), ...value.settlements.map((v) => [paths.settlements, v.id, v] as [string, string, unknown]), ...(value.recurringTemplates as RecurringTemplate[]).map((v) => [paths.recurringTemplates, v.id, v] as [string, string, unknown])];
    await runTransaction(this.db, async (tx) => { for (const [name, id, v] of refs) tx.set(name === "households" ? this.household(id) : this.item(h, name, id), toFirestoreData(v as object), { merge: false }); tx.set(this.item(h, "config", "current"), toFirestoreData(value.currentConfig), { merge: false }); for (const event of (value.auditLog ?? []) as AuditEvent[]) tx.set(this.item(h, paths.auditLog, event.id), toFirestoreData(event), { merge: false }); const audit: AuditEvent = { id: `audit-restore-${Date.now()}`, eventType: "backup restored", entityType: "household", entityId: h, performedByUid: actorUid, timestamp: new Date().toISOString(), summary: "Portable backup restored" }; tx.set(this.item(h, paths.auditLog, audit.id), toFirestoreData(audit), { merge: false }); }); }
  /** Restore path for a household whose root and UID-keyed member allowlist were provisioned out of band. */
  async restoreIntoProvisionedHousehold(h: Id, raw: BudgetExportV1, actorUid: string) {
    assertValidBudgetExport(raw);
    const value = raw;
    const root = await getDoc(this.household(h));
    if (!root.exists()) throw new Error("Restore target household must be provisioned first");
    const existingMembers = await this.getMembers(h);
    const expected = new Map(value.members.map((member) => [member.id, member.authUid]));
    if (existingMembers.length !== value.members.length || existingMembers.some((member) => expected.get(member.id) !== member.authUid)) throw new Error("Restore target membership does not match backup");
    const economicNames = Object.values(paths).filter((name) => name !== paths.members);
    const existingCollections = await Promise.all(economicNames.map((name) => getDocs(this.col(h, name))));
    if (existingCollections.some((snap) => !snap.empty)) throw new Error("Restore target economic collections must be empty");
    const refs: Array<[string, string, unknown]> = [
      ...value.accounts.map((v) => [paths.accounts, v.id, v] as [string, string, unknown]), ...value.categories.map((v) => [paths.categories, v.id, v] as [string, string, unknown]),
      ...value.projects.map((v) => [paths.projects, v.id, v] as [string, string, unknown]), ...value.settlementPools.map((v) => [paths.settlementPools, v.id, v] as [string, string, unknown]),
      ...value.configHistory.map((v) => [paths.configHistory, v.id, v] as [string, string, unknown]), ...value.settlementPeriods.map((v) => [paths.settlementPeriods, v.id, v] as [string, string, unknown]),
      ...value.transactions.map((v) => [paths.transactions, v.id, v] as [string, string, unknown]), ...value.settlements.map((v) => [paths.settlements, v.id, v] as [string, string, unknown]),
      ...(value.recurringTemplates as RecurringTemplate[]).map((v) => [paths.recurringTemplates, v.id, v] as [string, string, unknown]),
    ];
    await runTransaction(this.db, async (transaction) => {
      for (const [name, id, entity] of refs) transaction.set(this.item(h, name, id), toFirestoreData(entity as object), { merge: false });
      transaction.set(this.item(h, "config", "current"), toFirestoreData({ versionId: value.currentConfig.id, ...value.currentConfig }), { merge: false });
      for (const audit of (value.auditLog ?? []) as AuditEvent[]) transaction.set(this.item(h, paths.auditLog, audit.id), toFirestoreData(audit), { merge: false });
      transaction.set(this.item(h, paths.auditLog, `audit-restore-${Date.now()}`), toFirestoreData({ eventType: "backup restored", entityType: "household", entityId: h, performedByUid: actorUid, timestamp: new Date().toISOString(), summary: "Portable backup restored" }), { merge: false });
    });
  }
}
