import type { Account, Category, FinalizedSettlement, Household, HouseholdConfigVersion, HouseholdMember, Id, Project, RecurringTemplate, SettlementPeriod, SettlementPool, Transaction } from "../domain/types";
import { validateTransaction } from "../domain/validation";
import type { AuditEvent, BudgetRepository, TransactionDateQuery } from "./BudgetRepository";
import { assertValidBudgetExport, type BudgetExportV1 } from "../services/export";

const copy = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const now = () => new Date().toISOString();
const mapValues = <T extends { id: Id }>(map: Map<Id, T>) => [...map.values()].map(copy);
const ensureMoney = (n: number) => { if (!Number.isInteger(n) || n < 0) throw new Error("Money must be a non-negative integer number of cents"); };

export class InMemoryBudgetRepository implements BudgetRepository {
  private households = new Map<Id, Household>(); private members = new Map<Id, Map<Id, HouseholdMember>>();
  private accounts = new Map<Id, Map<Id, Account>>(); private categories = new Map<Id, Map<Id, Category>>(); private projects = new Map<Id, Map<Id, Project>>(); private pools = new Map<Id, Map<Id, SettlementPool>>();
  private configs = new Map<Id, Map<Id, HouseholdConfigVersion>>(); private currentConfigs = new Map<Id, HouseholdConfigVersion>(); private periods = new Map<Id, Map<Id, SettlementPeriod>>(); private transactions = new Map<Id, Map<Id, Transaction>>(); private settlements = new Map<Id, Map<Id, FinalizedSettlement>>(); private templates = new Map<Id, Map<Id, RecurringTemplate>>(); private audits = new Map<Id, Map<Id, AuditEvent>>();
  private bucket<T>(root: Map<Id, Map<Id, T>>, householdId: Id) { let value = root.get(householdId); if (!value) { value = new Map(); root.set(householdId, value); } return value; }
  private required<T>(value: T | undefined, label: string): T { if (!value) throw new Error(`${label} not found`); return copy(value); }
  seedHousehold(household: Household): void { this.households.set(household.id, copy(household)); }
  seed<T extends { id: Id }>(householdId: Id, collection: "members" | "accounts" | "categories" | "projects" | "pools" | "periods" | "transactions" | "settlements" | "templates", values: T[]): void { const roots = { members: this.members, accounts: this.accounts, categories: this.categories, projects: this.projects, pools: this.pools, periods: this.periods, transactions: this.transactions, settlements: this.settlements, templates: this.templates } as unknown as Record<string, Map<Id, Map<Id, { id: Id }>>>; const target = this.bucket(roots[collection], householdId); for (const value of values) target.set(value.id, copy(value)); }
  async getHousehold(id: Id) { return this.required(this.households.get(id), "Household"); }
  async saveHousehold(id: Id, value: Household) { if (id !== value.id) throw new Error("Household ID mismatch"); this.households.set(id, copy(value)); }
  async getMembers(id: Id) { return mapValues(this.bucket(this.members, id)); } async saveMember(h: Id, v: HouseholdMember) { this.bucket(this.members, h).set(v.id, copy(v)); }
  async getAccounts(id: Id) { return mapValues(this.bucket(this.accounts, id)); } async saveAccount(h: Id, v: Account) { this.bucket(this.accounts, h).set(v.id, copy(v)); }
  async getCategories(id: Id) { return mapValues(this.bucket(this.categories, id)); } async saveCategory(h: Id, v: Category) { this.bucket(this.categories, h).set(v.id, copy(v)); }
  async getProjects(id: Id) { return mapValues(this.bucket(this.projects, id)); } async saveProject(h: Id, v: Project) { this.bucket(this.projects, h).set(v.id, copy(v)); }
  async getSettlementPools(id: Id) { return mapValues(this.bucket(this.pools, id)); } async saveSettlementPool(h: Id, v: SettlementPool) { this.bucket(this.pools, h).set(v.id, copy(v)); }
  async getCurrentConfig(id: Id) { return this.required(this.currentConfigs.get(id), "Current config"); }
  async getConfigForDate(h: Id, effectiveAt: string) { const candidates = mapValues(this.bucket(this.configs, h)).filter((config) => config.effectiveFrom <= effectiveAt).sort((a, b) => a.effectiveFrom.localeCompare(b.effectiveFrom) || a.version - b.version); return this.required(candidates.at(-1) ?? this.currentConfigs.get(h), "Config for date"); }
  async getConfigVersion(h: Id, id: Id) { return this.required(this.bucket(this.configs, h).get(id), "Config version"); }
  async saveConfig(h: Id, v: HouseholdConfigVersion, reason?: string) { const value = reason === undefined ? v : { ...v, reason }; if (value.defaultAllocations.reduce((sum, a) => sum + a.shareBasisPoints, 0) !== 10000) throw new Error("Allocations must total 10000 basis points"); for (const n of Object.values(value.monthlyContributions)) ensureMoney(n); const history = this.bucket(this.configs, h); if (history.has(value.id) && JSON.stringify(history.get(value.id)) !== JSON.stringify(value)) throw new Error("Config history is immutable"); history.set(value.id, copy(value)); if (value.effectiveFrom <= now() || !this.currentConfigs.has(h)) this.currentConfigs.set(h, copy(value)); }
  async listConfigHistory(h: Id) { return mapValues(this.bucket(this.configs, h)).sort((a, b) => a.version - b.version); }
  async getSettlementPeriod(h: Id, id: Id) { return this.required(this.bucket(this.periods, h).get(id), "Settlement period"); }
  async listSettlementPeriods(h: Id) { return mapValues(this.bucket(this.periods, h)).sort((a, b) => b.startDate.localeCompare(a.startDate)); }
  async saveSettlementPeriod(h: Id, v: SettlementPeriod, expected?: string) { const existing = this.bucket(this.periods, h).get(v.id); if (expected && existing?.updatedAt !== expected) throw new Error("Concurrency conflict: settlement period changed"); this.bucket(this.periods, h).set(v.id, copy(v)); }
  async saveBootstrap(h: Id, period: SettlementPeriod, transactions: Transaction[]) { const periods = this.bucket(this.periods, h); if (periods.has(period.id)) throw new Error("Concurrency conflict: month already bootstrapped"); periods.set(period.id, copy(period)); const target = this.bucket(this.transactions, h); for (const transaction of transactions) if (!target.has(transaction.id)) target.set(transaction.id, copy(transaction)); }
  async listTransactionsForPeriod(h: Id, p: Id) { return mapValues(this.bucket(this.transactions, h)).filter((v) => v.settlementPeriodId === p).sort((a, b) => a.economicDate.localeCompare(b.economicDate)); }
  async getTransaction(h: Id, id: Id) { return this.required(this.bucket(this.transactions, h).get(id), "Transaction"); }
  async saveTransaction(h: Id, v: Transaction, expected?: string) { ensureMoney(v.amountCents); const validation = validateTransaction(v, { members: await this.getMembers(h), accounts: await this.getAccounts(h), categories: await this.getCategories(h), projects: await this.getProjects(h), settlementPools: await this.getSettlementPools(h) }); if (!validation.valid) throw new Error(`Invalid transaction: ${validation.errors.join("; ")}`); const existing = this.bucket(this.transactions, h).get(v.id); if (expected && existing?.updatedAt !== expected) throw new Error("Concurrency conflict: transaction changed"); const oldPeriod = existing?.settlementPeriodId ? this.bucket(this.periods, h).get(existing.settlementPeriodId) : undefined; const newPeriod = v.settlementPeriodId ? this.bucket(this.periods, h).get(v.settlementPeriodId) : undefined; if (oldPeriod?.status === "finalized" || newPeriod?.status === "finalized") throw new Error("Finalized period transactions cannot be edited until reopened"); const touched = new Set([oldPeriod?.id, newPeriod?.id]); const timestamp = v.updatedAt || now(); for (const periodId of touched) { if (!periodId) continue; const period = this.bucket(this.periods, h).get(periodId); if (period) this.bucket(this.periods, h).set(periodId, { ...period, updatedAt: timestamp, updatedByUid: v.updatedByUid }); } this.bucket(this.transactions, h).set(v.id, copy(v)); }
  async archiveTransaction(h: Id, id: Id, actorUid: string, reason = "Archived") { const tx = await this.getTransaction(h, id); tx.status = "excluded"; tx.updatedByUid = actorUid; tx.updatedAt = now(); await this.saveTransaction(h, tx); await this.appendAuditEvent(h, { id: `audit-${id}-${Date.now()}`, eventType: "transaction deleted/excluded", entityType: "transaction", entityId: id, performedByUid: actorUid, timestamp: now(), summary: reason }); }
  private query(h: Id, field: keyof Transaction, value: Id, range?: TransactionDateQuery) { return mapValues(this.bucket(this.transactions, h)).filter((tx) => tx[field] === value && (!range?.from || tx.economicDate >= range.from) && (!range?.to || tx.economicDate <= range.to)).sort((a, b) => a.economicDate.localeCompare(b.economicDate)); }
  async listTransactionsByProject(h: Id, p: Id) { return this.query(h, "projectId", p); } async listTransactionsByAccount(h: Id, a: Id, r?: TransactionDateQuery) { return this.query(h, "accountId", a, r); } async listTransactionsByCategory(h: Id, c: Id, r?: TransactionDateQuery) { return this.query(h, "categoryId", c, r); }
  async getFinalizedSettlementForPeriod(h: Id, p: Id) { const values = mapValues(this.bucket(this.settlements, h)).filter((s) => s.settlementPeriodId === p).sort((a, b) => b.version - a.version); return values[0] ?? null; }
  async saveSettlement(h: Id, v: FinalizedSettlement) { const target = this.bucket(this.settlements, h); if (target.has(v.id)) throw new Error("Finalized settlement snapshots are immutable"); target.set(v.id, copy(v)); }
  async commitFinalization(h: Id, settlement: FinalizedSettlement, period: SettlementPeriod, audit: AuditEvent, expected: string) { const current = this.bucket(this.periods, h).get(period.id); if (!current || current.updatedAt !== expected) throw new Error("Concurrency conflict: period changed during finalization"); await this.saveSettlement(h, settlement); this.bucket(this.periods, h).set(period.id, copy(period)); await this.appendAuditEvent(h, audit); }
  async getSettlement(h: Id, id: Id) { return this.required(this.bucket(this.settlements, h).get(id), "Settlement"); }
  async getRecurringTemplates(h: Id) { return mapValues(this.bucket(this.templates, h)); } async saveRecurringTemplate(h: Id, v: RecurringTemplate) { this.bucket(this.templates, h).set(v.id, copy(v)); }
  async listAuditLog(h: Id) { return mapValues(this.bucket(this.audits, h)).sort((a, b) => a.timestamp.localeCompare(b.timestamp)); } async appendAuditEvent(h: Id, v: AuditEvent) { const target = this.bucket(this.audits, h); if (target.has(v.id) && JSON.stringify(target.get(v.id)) !== JSON.stringify(v)) throw new Error("Audit events are immutable"); target.set(v.id, copy(v)); }
  async exportAll(h: Id): Promise<BudgetExportV1> { const household = await this.getHousehold(h); return { format: "household-budget-export", schemaVersion: 1, exportedAt: now(), appVersion: "0.1.0", household, members: await this.getMembers(h), accounts: await this.getAccounts(h), categories: await this.getCategories(h), projects: await this.getProjects(h), settlementPools: await this.getSettlementPools(h), currentConfig: await this.getCurrentConfig(h), configHistory: await this.listConfigHistory(h), transactions: mapValues(this.bucket(this.transactions, h)), settlementPeriods: await this.listSettlementPeriods(h), settlements: mapValues(this.bucket(this.settlements, h)), recurringTemplates: await this.getRecurringTemplates(h) as RecurringTemplate[], auditLog: await this.listAuditLog(h) }; }
  async restoreAll(h: Id, raw: BudgetExportV1, actorUid: string) { assertValidBudgetExport(raw); const value = raw; if (this.households.has(h) || [this.members, this.accounts, this.categories, this.projects, this.pools, this.configs, this.periods, this.transactions, this.settlements, this.templates, this.audits].some((root) => root.get(h)?.size)) throw new Error("Restore target must be an empty household"); const remapped = copy(value); remapped.household = { ...remapped.household, id: h, updatedAt: now() }; this.seedHousehold(remapped.household); this.seed(h, "members", remapped.members); this.seed(h, "accounts", remapped.accounts); this.seed(h, "categories", remapped.categories); this.seed(h, "projects", remapped.projects); this.seed(h, "pools", remapped.settlementPools); this.seed(h, "periods", remapped.settlementPeriods); this.seed(h, "transactions", remapped.transactions); this.seed(h, "settlements", remapped.settlements); this.seed(h, "templates", remapped.recurringTemplates as RecurringTemplate[]); for (const cfg of remapped.configHistory) await this.saveConfig(h, cfg); for (const event of (remapped.auditLog ?? []) as AuditEvent[]) await this.appendAuditEvent(h, event); await this.appendAuditEvent(h, { id: `audit-restore-${Date.now()}`, eventType: "backup restored", entityType: "household", entityId: h, performedByUid: actorUid, timestamp: now(), summary: "Portable backup restored" }); }
}
